<?php
$ThemeStyleSetting_DefaultConfig_autoDefault= array(
'skin_selected_' =>  'GreenSkin',
'logo2x_' =>  array (
  'url' => 'http://wow.test/wp-content/uploads/2017/08/ch_fw_logo_big.png',
  'id' => '121',
  'height' => '75',
  'width' => '218',
  'thumbnail' => 'http://wow.test/wp-content/uploads/2017/08/ch_fw_logo_big-150x75.png',
),
'logo2x_mini_' =>  array (
  'url' => 'http://wow.test/wp-content/uploads/2017/08/ch_fw_logo3.png',
  'id' => '122',
  'height' => '52',
  'width' => '151',
  'thumbnail' => 'http://wow.test/wp-content/uploads/2017/08/ch_fw_logo3-150x52.png',
),
'siteBodyLayoutSetting_' =>  'boxed',
);
$MainPageSetting_DefaultConfig_autoDefault= array(
'android_theme_color_' =>  '#21b68e',
'body_font_two_' =>  '#c1c0c0',
'siteBodyBackgroundOptions_' =>  array (
  'background-color' => '#fff',
  'background-repeat' => '',
  'background-size' => '',
  'background-attachment' => '',
  'background-position' => '',
  'background-image' => '',
  'media' => 
  array (
    'id' => '',
    'height' => '',
    'width' => '',
    'thumbnail' => '',
  ),
),
'EntriePage_typography_' =>  array (
  'font-weight' => '',
  'font-style' => '',
  'font-size' => '14px',
  'line-height' => '14px',
  'color' => '#333',
),
'SiteCenterBorder_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'solid',
  'border-color' => '#efefef',
),
'SiteCenterBoxShadowEnableDisable_' =>  '0',
'SiteCenterBoxShadow_BgColor_' =>  array (
  'color' => '#000',
  'alpha' => '1',
  'rgba' => 'rgba(0,0,0,0.35)',
),
'SiteCenter_BgColor_' =>  '#ffffff',
'loadmore_BgColor_' =>  '#21b68e',
'loadmore_TextColor_' =>  '#ffffff',
'pagination_ButtonBgColor_' =>  '#21b68e',
'pagination_ButtonTextColor_' =>  '#ffffff',
'pagination_ActiveButtonBgColor_' =>  '#37bd99',
'pagination_ActiveButtonTextColor_' =>  '#ffffff',
);
$TopNavBarSetting_DefaultConfig_autoDefault= array(
'top-navbarBG_color_' =>  '#21b68e',
'top-navbar_dropdownBoxShadowEnableDisable_' =>  '1',
'top-megaMenu_BoxShadow_color_' =>  '#21b68e',
'top-navbar_border_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '#37bd99',
),
'top-navbar_typography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'uppercase',
  'font-size' => '14px',
  'line-height' => '15px',
  'color' => '#ffffff',
),
'top-navbar_text_shadow_color_' =>  'transparent',
'top-navbar_icon_color_' =>  '#ffffff',
);
$headerSetting_DefaultConfig_autoDefault= array(
'shop_mini_cart_enable_disable_' =>  '1',
'headerCenter_bgcolor_' =>  '#21b68e',
'HeaderCenter_Typography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'font-size' => '14px',
  'line-height' => '14px',
  'color' => '#ffffff',
),
'HeaderCenter_border_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '0',
  'border-left' => '0',
  'border-style' => 'none',
  'border-color' => '',
),
'headerCenter_makeAnAppoinmentBgColor_' =>  '#b5ef4a',
'headerCenter_makeAnAppoinment_Button_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => 'true',
  'font-weight' => '700',
  'font-style' => '',
  'text-transform' => 'capitalize',
  'font-size' => '',
  'line-height' => '',
  'color' => '',
),
'headerCenter_siearchButtonBgColor_' =>  '#1ea480',
'headerCenter_searchButtonBorder_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '#1ea480',
),
'HeaderCenter_SearchButtonTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'font-size' => '13px',
  'line-height' => '30px',
  'color' => '#fff',
),
'header_minicart_cartBgColor_' =>  '#000000',
'header_minicart_cartCounterBgColor_' =>  '#40ce93',
'header_minicart_cartCountertextColor_' =>  '#ffffff',
'header_minicart_BgColor_' =>  '#ffffff',
'header_minicart_Text_and_Link_Color_' =>  '#20bfb7',
'header_minicart_Border_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'none',
  'border-color' => '#000',
),
'header_minicart_editCartButton_BgColor_' =>  '#1dad7f',
'header_minicart_editCartButton_textColor_' =>  '#ffffff',
'header_minicart_checkoutButton_BgColor_' =>  '#1dad7f',
'header_minicart_checkoutButton_textColor_' =>  '#ffffff',
);
$menuSetting_DefaultConfig_autoDefault= array(
'megaMenu_menu_arrow_' =>  'hide',
'megaMenu_submenu_arrow_' =>  'hide',
'megaMenu_animation_type_' =>  'nothing',
'megaMenu_backgroundcolor_' =>  '#ffffff',
'megaMenu_backgroundHoverColor_' =>  '#ffffff',
'megaMenu_textcolor_' =>  '#000000',
'megaMenu_textHoverColor_' =>  '#81d742',
'megaMenu_Typography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'uppercase',
  'font-size' => '13px',
),
'megaMenu_topMenuBorderOption_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'none',
  'border-color' => '#1ea480',
),
'megaMenu_insideMenuTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'text-transform' => 'none',
),
'megaMenu_insideMenu_backgroundcolor_' =>  '#21b68e',
'megaMenu_insideMenu_Color' =>  '#ffffff',
'megaMenu_insideMenu_TextHoverColor_' =>  '#ffffff',
'megaMenu_insideMenu_ActiveBgColor_' =>  '#81d742',
'megaMenu_insideMenu_ActiveTextColor_' =>  '#ffffff',
'megaMenu_insideMenu_borderOption_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'none',
  'border-color' => '#355100',
),
'dropdown_menu-border-bottom_text_option_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '#1ea480',
),
);
$mobileMenuSetting_DefaultConfig_autoDefault= array(
'MobileMenu_BgColor_' =>  '#1ea480',
'MobileMenu_Submenu_BgColor_' =>  '#1ea480',
'MobileMenu_linkColor_' =>  '#ffffff',
'MobileMenu_arrowColor_' =>  '#ffffff',
'MobileMenu_searchButtonBgColor_' =>  '#21b68e',
'MobileMenu_searchButtonBorderColor_' =>  '#ffffff',
'MobileMenu_searchButtonTextColor_' =>  '#ffffff',
);
$MobileMenuAdvancedSettings_DefaultConfig_autoDefault= array(
'OutSideSidebar_BgColor_' =>  '#ffffff',
'OutSideSidebar_social_EnableDisable_' =>  '#93af76',
'OutSideSidebar_linkColor_' =>  '#8c8c8c',
'OutSideSidebar_arrowColor_' =>  '#8c8c8c',
'OutSideSidebar_searchButtonBgColor_' =>  '#ffffff',
'OutSideSidebar_searchButtonBorderColor_' =>  '#8c8c8c',
'OutSideSidebar_searchButtonTextColor_' =>  '#000000',
);
$blogPostListStyle_DefaultConfig_autoDefault= array(
'BlogPostTitleStyleTypography_' =>  array (
  'font-family' => '',
  'font-options' => '',
  'google' => '1',
  'font-backup' => '',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => '',
  'font-size' => '',
  'line-height' => '',
  'color' => '',
),
'BlogPostStyleInfoTypography_' =>  array (
  'font-family' => '',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => '',
  'font-size' => '',
  'line-height' => '',
  'color' => '',
),
'BlogPostStyleTextTypography_' =>  array (
  'font-family' => '',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => '',
  'font-size' => '',
  'line-height' => '',
  'color' => '',
),
'PostStyleListBgColor_' =>  '',
'PostStyleListBoxShadow_' =>  '',
'PostStyleListBorderRadius_' =>  '0',
'PostStyleListBorder_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '0',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '',
),
'PostStyleListSocialBarBgColor_' =>  '',
'PostStyleList_TagTypography_' =>  array (
  'font-family' => '',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => '',
  'font-size' => '',
  'line-height' => '',
  'color' => '',
),
'PostStyleList_TagHoverTypography_' =>  array (
  'font-family' => '',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => '',
  'font-size' => '',
  'line-height' => '',
  'color' => '',
),
'PostStyleList_TagsBgColor_' =>  '',
'PostStyleList_TagsHoverBgColor_' =>  '',
'PostStyleList_SocialBarBorder_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '0',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '',
),
'PostStyleList_ReadMoreButtonBgColor_' =>  '#21b68e',
'PostStyleList_ReadMoreButtonBgHoverColor_' =>  '#24c992',
'BlogPostStyleReadMoreButtonTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '14px',
  'line-height' => '14px',
  'color' => '#ffffff',
),
'BlogPostStyleReadMoreButtonHoverTypography_' =>  '#ffffff',
);
$sidebarStyle_DefaultConfig_autoDefault= array(
'sidebar_view_model_' =>  'unboxed',
'sidebar_widget_BgColor_' =>  '#ffffff',
'sidebar_widget_Border_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'solid',
  'border-color' => '#efefef',
),
'sidebar_widgetBoxShadowEnableDisable_' =>  '0',
'sidebar_BoxShadow_BgColor_' =>  array (
  'color' => '#000',
  'alpha' => '1',
  'rgba' => 'rgba(0,0,0,0.35)',
),
'sidebar_widget_Linkcolor_' =>  '#000000',
'sidebar_widget_Textcolor_' =>  '#000000',
'sidebar_widget_title_selected' =>  'colored_widget',
'sidebar_widget_title_typography_custom_skin_border_bottom_bg_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#d84f5f',
),
'sidebar_widget_title_typography_custom_skin_border_bottom_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000000',
),
'sidebar_widget_title_typography_custom_skin_line_left_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'sidebar_widget_title_typography_custom_skin_line_transparant_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'uppercase',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#d84f5f',
),
'sidebar_widget_title_typography_custom_skin_line_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'center',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'sidebar_widget_title_typography_custom_skin_colored_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-align' => 'center',
  'text-transform' => 'capitalize',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#ffffff',
),
'sidebar_widget_title_typography_custom_skin_colored_two_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'sidebar_widget_title_BgColor_first_custom_skin_border_bottom_bg_widget' =>  '#252525',
'sidebar_widget_title_BgColor_first_custom_skin_colored_two_widget' =>  '#252525',
'sidebar_widget_title_BgColor_first_custom_skin_colored_widget' =>  '#21b68e',
'sidebar_widget_title_BgColor_first_custom_skin_line_widget' =>  '#ffffff',
'sidebar_widget_title_BgColor_first_custom_skin_line_left_widget' =>  '#ffffff',
'sidebar_widget_title_BgColor_second_border_bottom_bg_widget' =>  '#F4524C',
'sidebar_widget_title_BgColor_second_border_bottom_widget' =>  'transparent',
'sidebar_widget_title_LineColor' =>  '#000000',
'sidebar_widget_title_colored_widgetTopBorderColor' =>  '#ffc908',
'sidebar_widget_title_borderColor' =>  '#000000',
'sidebar_widget_title_TagbgColor_' =>  '#21b68e',
'sidebar_widget_title_Tag_HoverbgColor_' =>  '#27db6f',
'sidebar_widget_TagsWidgetBorder_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'solid',
  'border-color' => '#e4e4e4',
),
'sidebar_widget_title_TagWidgetTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '15px',
  'color' => '#ffffff',
),
'sidebar_widget_title_WidgetHoverTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '15px',
  'color' => '#b5b5b5',
),
'sidebar_widget_searchButtonBgColor_' =>  '#21b68e',
'sidebar_widget_searchButton_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'uppercase',
  'font-size' => '14px',
  'line-height' => '28px',
  'color' => '#fff',
),
);
$shopsetting_DefaultConfig_autoDefault= array(
'Shop_product_image_bgcolor_' =>  '',
'Shop_sale_badge_textcolor_' =>  '#ffffff',
'Shop_sale_badge_bgcolor_' =>  '#81d742',
'Shop_outofstock_badge_bgcolor_' =>  '#333333',
'Shop_new_badge_bgcolor_' =>  '#07acb5',
'Shop_discountPercentage_' =>  '#dd3333',
'Shop_quickview_bgcolor_' =>  '#28efd1',
'AddToCart_btn_BgColor_' =>  '#1dad7f',
'AddToCart_btn_TextColor_' =>  '#ffffff',
);
$FooterStyle_DefaultConfig_autoDefault= array(
'footer_widget_BgColor_' =>  '#1ea480',
'footer_widget_Border_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '0',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '#1a9272',
),
'footer_widget_Linkcolor_' =>  '#ffffff',
'footer_widget_Textcolor_' =>  '#ffffff',
'footer_widget_title_selected' =>  'border_bottom_widget',
'footer_widget_title_typography_custom_skin_border_bottom_bg_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#d84f5f',
),
'footer_widget_title_typography_custom_skin_border_bottom_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#ffffff',
),
'footer_widget_title_typography_custom_skin_line_left_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'footer_widget_title_typography_custom_skin_line_transparant_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-align' => 'center',
  'text-transform' => 'uppercase',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'footer_widget_title_typography_custom_skin_line_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'center',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'footer_widget_title_typography_custom_skin_colored_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'footer_widget_title_typography_custom_skin_colored_two_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'footer_widget_title_BgColor_first_custom_skin_border_bottom_bg_widget' =>  '#252525',
'footer_widget_title_BgColor_first_custom_skin_colored_two_widget' =>  '#252525',
'footer_widget_title_BgColor_first_custom_skin_colored_widget' =>  '#252525',
'footer_widget_title_BgColor_first_custom_skin_line_widget' =>  '#ffffff',
'footer_widget_title_BgColor_first_custom_skin_line_left_widget' =>  '#ffffff',
'footer_widget_title_BgColor_second_border_bottom_bg_widget' =>  '#F4524C',
'footer_widget_title_BgColor_second_border_bottom_widget' =>  '#ffffff',
'footer_widget_title_LineColor' =>  '#000000',
'footer_widget_title_top_borderColor' =>  '#ffc908',
'footer_widget_title_borderColor' =>  '#1a9272',
'footer_widget_title_TagbgColor_' =>  '#1a9272',
'footer_widget_title_Tag_HoverbgColor_' =>  '#27db6f',
'footer_widget_TagsWidgetBorder_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'solid',
  'border-color' => '#e4e4e4',
),
'footer_widget_title_TagWidgetTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '15px',
  'color' => '#ffffff',
),
'footer_widget_title_TagWidgetHoverTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '15px',
  'color' => '#fff',
),
'footer_widget_searchButtonBgColor_' =>  '#d85060',
'footer_widget_searchButton_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'uppercase',
  'font-size' => '14px',
  'line-height' => '28px',
  'color' => '#fff',
),
'footer_minimal_widget_BgColor_' =>  '#21b68e',
'footer_minimal_widget_Border_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'solid',
  'border-color' => '#1a9272',
),
'footer_minimal_widget_Linkcolor_' =>  '#ffffff',
'footer_minimal_widget_Textcolor_' =>  '#ffffff',
);
