<?php
$ThemeStyleSetting_DefaultConfig_autoDefault= array(
'skin_selected_' =>  'Hospital',
'logo2x_' =>  array (
  'url' => 'http://wow.test/wp-content/uploads/2018/04/logos.png',
  'id' => '960',
  'height' => '65',
  'width' => '151',
  'thumbnail' => 'http://wow.test/wp-content/uploads/2018/04/logos-150x65.png',
  'title' => 'logos',
  'caption' => '',
  'alt' => '',
  'description' => '',
),
'logo2x_mini_' =>  array (
  'url' => 'http://wow.test/wp-content/uploads/2018/04/logos.png',
  'id' => '960',
  'height' => '65',
  'width' => '151',
  'thumbnail' => 'http://wow.test/wp-content/uploads/2018/04/logos-150x65.png',
  'title' => 'logos',
  'caption' => '',
  'alt' => '',
  'description' => '',
),
'siteBodyLayoutSetting_' =>  'stretched',
);
$MainPageSetting_DefaultConfig_autoDefault= array(
'android_theme_color_' =>  '#0392ce',
'body_font_two_' =>  '#c1c0c0',
'siteBodyBackgroundOptions_' =>  array (
  'background-color' => '#ffffff',
  'background-repeat' => '',
  'background-size' => '',
  'background-attachment' => '',
  'background-position' => '',
  'background-image' => '',
  'media' => 
  array (
    'id' => '',
    'height' => '',
    'width' => '',
    'thumbnail' => '',
  ),
),
'EntriePage_typography_' =>  array (
  'font-weight' => '400',
  'font-style' => '',
  'font-size' => '12px',
  'line-height' => '12px',
  'color' => '#888888',
),
'SiteCenterBorder_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'none',
  'border-color' => '#D7D7D7',
),
'SiteCenterBoxShadowEnableDisable_' =>  '0',
'SiteCenterBoxShadow_BgColor_' =>  array (
  'color' => '#000',
  'alpha' => '1',
  'rgba' => 'rgba(0,0,0,0.35)',
),
'SiteCenter_BgColor_' =>  'transparent',
'loadmore_BgColor_' =>  '#4285f4',
'loadmore_TextColor_' =>  '#ffffff',
'pagination_ButtonBgColor_' =>  '#4285f4',
'pagination_ButtonTextColor_' =>  '#ffffff',
'pagination_ActiveButtonBgColor_' =>  '#85b0f8',
'pagination_ActiveButtonTextColor_' =>  '#ffffff',
);
$TopNavBarSetting_DefaultConfig_autoDefault= array(
'top-navbarBG_color_' =>  '#ffffff',
'top-navbar_dropdownBoxShadowEnableDisable_' =>  '0',
'top-megaMenu_BoxShadow_color_' =>  'transparent',
'top-navbar_border_' =>  array (
  'border-top' => '0.5px',
  'border-right' => '0.5px',
  'border-bottom' => '0.5px',
  'border-left' => '0.5px',
  'border-style' => 'solid',
  'border-color' => '#efefef',
),
'top-navbar_typography_' =>  array (
  'font-family' => 'Open Sans',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '400',
  'font-style' => '',
  'text-transform' => 'capitalize',
  'font-size' => '12px',
  'line-height' => '11px',
  'color' => '#000000',
),
'top-navbar_text_shadow_color_' =>  '#dddddd',
'top-navbar_icon_color_' =>  '#e2e2e2',
);
$headerSetting_DefaultConfig_autoDefault= array(
'shop_mini_cart_enable_disable_' =>  '0',
'headerCenter_bgcolor_' =>  '#ffffff',
'HeaderCenter_Typography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '400',
  'font-style' => '',
  'font-size' => '14px',
  'line-height' => '14px',
  'color' => '#ffffff',
),
'HeaderCenter_border_' =>  array (
  'border-top' => '0px',
  'border-right' => '0px',
  'border-bottom' => '1px',
  'border-left' => '0px',
  'border-style' => 'solid',
  'border-color' => '#969696',
),
'headerCenter_makeAnAppoinmentBgColor_' =>  '#058cc6',
'headerCenter_makeAnAppoinment_Button_' =>  array (
  'font-family' => 'Poppins',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '500',
  'font-style' => '',
  'text-transform' => 'uppercase',
  'font-size' => '11px',
  'color' => '#ffffff',
),
'headerCenter_siearchButtonBgColor_' =>  '#ffffff',
'headerCenter_searchButtonBorder_' =>  array (
  'border-top' => '2px',
  'border-right' => '2px',
  'border-bottom' => '2px',
  'border-left' => '2px',
  'border-style' => 'solid',
  'border-color' => '#ffffff',
),
'HeaderCenter_SearchButtonTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'font-size' => '13px',
  'line-height' => '30px',
  'color' => '#fff',
),
'header_minicart_cartBgColor_' =>  '#1e73be',
'header_minicart_cartCounterBgColor_' =>  '#f4524d',
'header_minicart_cartCountertextColor_' =>  '#000000',
'header_minicart_BgColor_' =>  '#ffffff',
'header_minicart_Text_and_Link_Color_' =>  '#004dac',
'header_minicart_Border_' =>  array (
  'border-top' => '0px',
  'border-right' => '0px',
  'border-bottom' => '1px',
  'border-left' => '0px',
  'border-style' => 'none',
  'border-color' => '#000',
),
'header_minicart_editCartButton_BgColor_' =>  '#004dac',
'header_minicart_editCartButton_textColor_' =>  '#f2ba53',
'header_minicart_checkoutButton_BgColor_' =>  '#f2ba53',
'header_minicart_checkoutButton_textColor_' =>  '#52191d',
);
$menuSetting_DefaultConfig_autoDefault= array(
'megaMenu_menu_arrow_' =>  'show',
'megaMenu_submenu_arrow_' =>  'hide',
'megaMenu_animation_type_' =>  'nothing',
'megaMenu_backgroundcolor_' =>  '#ffffff',
'megaMenu_backgroundHoverColor_' =>  '#ffffff',
'megaMenu_textcolor_' =>  '#000000',
'megaMenu_textHoverColor_' =>  '#347cdb',
'megaMenu_Typography_' =>  array (
  'font-family' => 'Open Sans',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '400',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '18px',
  'line-height' => '20px',
),
'megaMenu_topMenuBorderOption_' =>  array (
  'border-top' => '0.5px',
  'border-right' => '0.5px',
  'border-bottom' => '0.5px',
  'border-left' => '0.5px',
  'border-style' => 'solid',
  'border-color' => '#eeeeee',
),
'megaMenu_insideMenuTypography_' =>  array (
  'font-family' => 'Open Sans',
  'font-options' => '',
  'google' => '1',
  'text-transform' => 'none',
),
'megaMenu_insideMenu_backgroundcolor_' =>  '#ffffff',
'megaMenu_insideMenu_Color' =>  '#000000',
'megaMenu_insideMenu_TextHoverColor_' =>  '#347cdb',
'megaMenu_insideMenu_ActiveBgColor_' =>  '#ffffff',
'megaMenu_insideMenu_ActiveTextColor_' =>  '#347cdb',
'megaMenu_insideMenu_borderOption_' =>  array (
  'border-top' => '0px',
  'border-right' => '0px',
  'border-bottom' => '0px',
  'border-left' => '0px',
  'border-style' => 'none',
  'border-color' => '#000000',
),
'dropdown_menu-border-bottom_text_option_' =>  array (
  'border-top' => '0px',
  'border-right' => '0px',
  'border-bottom' => '1px',
  'border-left' => '0px',
  'border-style' => 'none',
  'border-color' => '#dddddd',
),
);
$mobileMenuSetting_DefaultConfig_autoDefault= array(
'MobileMenu_BgColor_' =>  '#ffffff',
'MobileMenu_Submenu_BgColor_' =>  '#ffffff',
'MobileMenu_linkColor_' =>  '#000000',
'MobileMenu_arrowColor_' =>  '#000000',
'MobileMenu_searchButtonBgColor_' =>  '#ffffff',
'MobileMenu_searchButtonBorderColor_' =>  '#8c8c8c',
'MobileMenu_searchButtonTextColor_' =>  '#000000',
);
$MobileMenuAdvancedSettings_DefaultConfig_autoDefault= array(
'OutSideSidebar_BgColor_' =>  '#ffffff',
'OutSideSidebar_social_EnableDisable_' =>  '#93af76',
'OutSideSidebar_linkColor_' =>  '#8c8c8c',
'OutSideSidebar_arrowColor_' =>  '#8c8c8c',
'OutSideSidebar_searchButtonBgColor_' =>  '#ffffff',
'OutSideSidebar_searchButtonBorderColor_' =>  '#8c8c8c',
'OutSideSidebar_searchButtonTextColor_' =>  '#000000',
);
$blogPostListStyle_DefaultConfig_autoDefault= array(
'BlogPostTitleStyleTypography_' =>  array (
  'font-family' => 'Poppins',
  'font-options' => '',
  'google' => '1',
  'font-backup' => '\'Comic Sans MS\', cursive',
  'font-weight' => '700',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '18px',
  'line-height' => '29px',
  'color' => '#494949',
),
'BlogPostStyleInfoTypography_' =>  array (
  'font-family' => 'Poppins',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '500',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '11px',
  'line-height' => '22px',
  'color' => '#595959',
),
'BlogPostStyleTextTypography_' =>  array (
  'font-family' => 'Poppins',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '400',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '13px',
  'line-height' => '22px',
  'color' => '#888888',
),
'PostStyleListBgColor_' =>  '#ffffff',
'PostStyleListBoxShadow_' =>  '1',
'PostStyleListBorderRadius_' =>  '0',
'PostStyleListBorder_' =>  array (
  'border-top' => '0px',
  'border-right' => '0px',
  'border-bottom' => '1px',
  'border-left' => '0px',
  'border-style' => 'none',
  'border-color' => '#d8d8d8',
),
'PostStyleListSocialBarBgColor_' =>  '',
'PostStyleList_TagTypography_' =>  array (
  'font-family' => '',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => '',
  'font-size' => '',
  'line-height' => '',
  'color' => '',
),
'PostStyleList_TagHoverTypography_' =>  array (
  'font-family' => '',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => '',
  'font-size' => '',
  'line-height' => '',
  'color' => '',
),
'PostStyleList_TagsBgColor_' =>  '',
'PostStyleList_TagsHoverBgColor_' =>  '',
'PostStyleList_SocialBarBorder_' =>  array (
  'border-top' => '0px',
  'border-right' => '0px',
  'border-bottom' => '0px',
  'border-left' => '0px',
  'border-style' => 'solid',
  'border-color' => '',
),
'PostStyleList_ReadMoreButtonBgColor_' =>  'transparent',
'PostStyleList_ReadMoreButtonBgHoverColor_' =>  'transparent',
'BlogPostStyleReadMoreButtonTypography_' =>  array (
  'font-family' => 'Open Sans',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '400',
  'font-style' => '',
  'text-transform' => 'capitalize',
  'font-size' => '12px',
  'line-height' => '14px',
  'color' => '#000000',
),
'BlogPostStyleReadMoreButtonHoverTypography_' =>  '#000000',
);
$sidebarStyle_DefaultConfig_autoDefault= array(
'sidebar_view_model_' =>  'boxed-content',
'sidebar_widget_BgColor_' =>  '#ffffff',
'sidebar_widget_Border_' =>  array (
  'border-top' => '0px',
  'border-right' => '0px',
  'border-bottom' => '0px',
  'border-left' => '0px',
  'border-style' => 'none',
  'border-color' => '#DDD',
),
'sidebar_widgetBoxShadowEnableDisable_' =>  '1',
'sidebar_BoxShadow_BgColor_' =>  array (
  'color' => '#000000',
  'alpha' => '0.1',
  'rgba' => 'rgba(0,0,0,0.1)',
),
'sidebar_widget_Linkcolor_' =>  '#000000',
'sidebar_widget_Textcolor_' =>  '#000000',
'sidebar_widget_title_selected' =>  'line_transparant_widget',
'sidebar_widget_title_typography_custom_skin_border_bottom_bg_widget' =>  array (
  'font-family' => 'Poppins',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '14px',
  'line-height' => '28px',
  'color' => '#579aed',
),
'sidebar_widget_title_typography_custom_skin_border_bottom_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000000',
),
'sidebar_widget_title_typography_custom_skin_line_left_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'sidebar_widget_title_typography_custom_skin_line_transparant_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '700',
  'font-style' => '',
  'text-align' => 'center',
  'text-transform' => 'uppercase',
  'font-size' => '17px',
  'line-height' => '28px',
  'color' => '#000000',
),
'sidebar_widget_title_typography_custom_skin_line_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'center',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'sidebar_widget_title_typography_custom_skin_colored_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'uppercase',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#ffffff',
),
'sidebar_widget_title_typography_custom_skin_colored_two_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'sidebar_widget_title_BgColor_first_custom_skin_border_bottom_bg_widget' =>  '#252525',
'sidebar_widget_title_BgColor_first_custom_skin_colored_two_widget' =>  '#dd3333',
'sidebar_widget_title_BgColor_first_custom_skin_colored_widget' =>  '#2d85c4',
'sidebar_widget_title_BgColor_first_custom_skin_line_widget' =>  '#ffffff',
'sidebar_widget_title_BgColor_first_custom_skin_line_left_widget' =>  '#ffffff',
'sidebar_widget_title_BgColor_second_border_bottom_bg_widget' =>  '#1e73be',
'sidebar_widget_title_BgColor_second_border_bottom_widget' =>  'transparent',
'sidebar_widget_title_LineColor' =>  '#000000',
'sidebar_widget_title_colored_widgetTopBorderColor' =>  '#ffc908',
'sidebar_widget_title_borderColor' =>  '#000000',
'sidebar_widget_title_TagbgColor_' =>  '#2d85c4',
'sidebar_widget_title_Tag_HoverbgColor_' =>  '#2d85c4',
'sidebar_widget_TagsWidgetBorder_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'solid',
  'border-color' => '#e4e4e4',
),
'sidebar_widget_title_TagWidgetTypography_' =>  array (
  'font-family' => 'Poppins',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '15px',
  'color' => '#ffffff',
),
'sidebar_widget_title_WidgetHoverTypography_' =>  array (
  'font-family' => 'Poppins',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '15px',
  'color' => '#000000',
),
'sidebar_widget_searchButtonBgColor_' =>  '#0072a8',
'sidebar_widget_searchButton_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '400',
  'font-style' => '',
  'text-transform' => 'uppercase',
  'font-size' => '14px',
  'line-height' => '28px',
  'color' => '#ffffff',
),
);
$shopsetting_DefaultConfig_autoDefault= array(
'Shop_product_image_bgcolor_' =>  '',
'Shop_sale_badge_textcolor_' =>  '#ffffff',
'Shop_sale_badge_bgcolor_' =>  '#dd336b',
'Shop_outofstock_badge_bgcolor_' =>  '#333333',
'Shop_new_badge_bgcolor_' =>  '#3885C5',
'Shop_discountPercentage_' =>  '#dd3333',
'Shop_quickview_bgcolor_' =>  '#08c08c',
'AddToCart_btn_BgColor_' =>  '#000000',
'AddToCart_btn_TextColor_' =>  '#ffffff',
);
$FooterStyle_DefaultConfig_autoDefault= array(
'footer_widget_BgColor_' =>  '#363839',
'footer_widget_Border_' =>  array (
  'border-top' => '0px',
  'border-right' => '0px',
  'border-bottom' => '0px',
  'border-left' => '0px',
  'border-style' => 'none',
  'border-color' => '',
),
'footer_widget_Linkcolor_' =>  '#ffffff',
'footer_widget_Textcolor_' =>  '#ffffff',
'footer_widget_title_selected' =>  'line_transparant_widget',
'footer_widget_title_typography_custom_skin_border_bottom_bg_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#d84f5f',
),
'footer_widget_title_typography_custom_skin_border_bottom_widget' =>  array (
  'font-family' => 'Poppins',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '14px',
  'line-height' => '20px',
  'color' => '#000000',
),
'footer_widget_title_typography_custom_skin_line_left_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '700',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#ffffff',
),
'footer_widget_title_typography_custom_skin_line_transparant_widget' =>  array (
  'font-family' => 'Open Sans',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '700',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'uppercase',
  'font-size' => '17px',
  'line-height' => '28px',
  'color' => '#ffffff',
),
'footer_widget_title_typography_custom_skin_line_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '700',
  'font-style' => '',
  'text-align' => 'center',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'footer_widget_title_typography_custom_skin_colored_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '700',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'footer_widget_title_typography_custom_skin_colored_two_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '700',
  'font-style' => '',
  'text-align' => 'center',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'footer_widget_title_BgColor_first_custom_skin_border_bottom_bg_widget' =>  '#252525',
'footer_widget_title_BgColor_first_custom_skin_colored_two_widget' =>  '#000000',
'footer_widget_title_BgColor_first_custom_skin_colored_widget' =>  '#252525',
'footer_widget_title_BgColor_first_custom_skin_line_widget' =>  '#ffffff',
'footer_widget_title_BgColor_first_custom_skin_line_left_widget' =>  'transparent',
'footer_widget_title_BgColor_second_border_bottom_bg_widget' =>  '#F4524C',
'footer_widget_title_BgColor_second_border_bottom_widget' =>  '#ffffff',
'footer_widget_title_LineColor' =>  '#000000',
'footer_widget_title_top_borderColor' =>  '#ffc908',
'footer_widget_title_borderColor' =>  '#cccccc',
'footer_widget_title_TagbgColor_' =>  '#515151',
'footer_widget_title_Tag_HoverbgColor_' =>  '#424242',
'footer_widget_TagsWidgetBorder_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'solid',
  'border-color' => '#515151',
),
'footer_widget_title_TagWidgetTypography_' =>  array (
  'font-family' => 'Poppins',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '400',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '11px',
  'line-height' => '10px',
  'color' => '#ffffff',
),
'footer_widget_title_TagWidgetHoverTypography_' =>  array (
  'font-family' => 'Poppins',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '15px',
  'color' => '#fff',
),
'footer_widget_searchButtonBgColor_' =>  '#1e73be',
'footer_widget_searchButton_' =>  array (
  'font-family' => 'Open Sans',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'uppercase',
  'font-size' => '14px',
  'line-height' => '28px',
  'color' => '#ffffff',
),
'footer_minimal_widget_BgColor_' =>  '#2f3232',
'footer_minimal_widget_Border_' =>  array (
  'border-top' => '0px',
  'border-right' => '0px',
  'border-bottom' => '0px',
  'border-left' => '0px',
  'border-style' => 'none',
  'border-color' => '#ece9e9',
),
'footer_minimal_widget_Linkcolor_' =>  '#bcbec0',
'footer_minimal_widget_Textcolor_' =>  '#bcbec0',
);
