<?php
$ThemeStyleSetting_DefaultConfig_autoDefault= array(
'skin_selected_' =>  'MinimalSkin',
'logo2x_' =>  array (
  'url' => 'http://wow.test/wp-content/uploads/2017/08/ch_fw_logo_big.png',
  'id' => '121',
  'height' => '75',
  'width' => '218',
  'thumbnail' => 'http://wow.test/wp-content/uploads/2017/08/ch_fw_logo_big-150x75.png',
),
'logo2x_mini_' =>  array (
  'url' => 'http://wow.test/wp-content/uploads/2017/08/ch_fw_logo3.png',
  'id' => '122',
  'height' => '52',
  'width' => '151',
  'thumbnail' => 'http://wow.test/wp-content/uploads/2017/08/ch_fw_logo3-150x52.png',
),
'siteBodyLayoutSetting_' =>  'stretched',
);
$MainPageSetting_DefaultConfig_autoDefault= array(
'android_theme_color_' =>  '#ffffff',
'body_font_two_' =>  '#c1c0c0',
'siteBodyBackgroundOptions_' =>  array (
  'background-color' => '#fff',
  'background-repeat' => '',
  'background-size' => '',
  'background-attachment' => '',
  'background-position' => '',
  'background-image' => '',
  'media' => 
  array (
    'id' => '',
    'height' => '',
    'width' => '',
    'thumbnail' => '',
  ),
),
'EntriePage_typography_' =>  array (
  'font-weight' => '',
  'font-style' => '',
  'font-size' => '14px',
  'line-height' => '14px',
  'color' => '#333',
),
'SiteCenterBorder_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'none',
  'border-color' => '#D7D7D7',
),
'SiteCenterBoxShadowEnableDisable_' =>  '0',
'SiteCenterBoxShadow_BgColor_' =>  array (
  'color' => 'rgba(0,0,0,0.35)',
  'alpha' => '1',
  'rgba' => 'rgba(0,0,0,0.35)',
),
'SiteCenter_BgColor_' =>  'transparent',
'loadmore_BgColor_' =>  '#303030',
'loadmore_TextColor_' =>  '#ffffff',
'pagination_ButtonBgColor_' =>  '#303030',
'pagination_ButtonTextColor_' =>  '#ffffff',
'pagination_ActiveButtonBgColor_' =>  '#999999',
'pagination_ActiveButtonTextColor_' =>  '#ffffff',
);
$TopNavBarSetting_DefaultConfig_autoDefault= array(
'top-navbarBG_color_' =>  '#E9E9E9',
'top-navbar_dropdownBoxShadowEnableDisable_' =>  '1',
'top-megaMenu_BoxShadow_color_' =>  'transparent',
'top-navbar_border_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '#e7e7e7',
),
'top-navbar_typography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'capitalize',
  'font-size' => '14px',
  'line-height' => '15px',
  'color' => '#555',
),
'top-navbar_text_shadow_color_' =>  'transparent',
'top-navbar_icon_color_' =>  '#555555',
);
$headerSetting_DefaultConfig_autoDefault= array(
'shop_mini_cart_enable_disable_' =>  '1',
'headerCenter_bgcolor_' =>  '#ffffff',
'HeaderCenter_Typography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'font-size' => '14px',
  'line-height' => '14px',
  'color' => '#777',
),
'HeaderCenter_border_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '0',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '',
),
'headerCenter_makeAnAppoinmentBgColor_' =>  'transparent',
'headerCenter_makeAnAppoinment_Button_' =>  array (
  'font-family' => 'Roboto',
  'font-options' => '',
  'google' => 'true',
  'font-weight' => '400',
  'font-style' => '',
  'text-transform' => '',
  'font-size' => '12px',
  'line-height' => '1px',
  'color' => '#ffffff',
),
'headerCenter_siearchButtonBgColor_' =>  '#ffffff',
'headerCenter_searchButtonBorder_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '#CCC',
),
'HeaderCenter_SearchButtonTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'font-size' => '13px',
  'line-height' => '30px',
  'color' => '#000',
),
'header_minicart_cartBgColor_' =>  '#000000',
'header_minicart_cartCounterBgColor_' =>  '#3f3f3f',
'header_minicart_cartCountertextColor_' =>  '#ffffff',
'header_minicart_BgColor_' =>  '#ffffff',
'header_minicart_Text_and_Link_Color_' =>  '#000000',
'header_minicart_Border_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '#000',
),
'header_minicart_editCartButton_BgColor_' =>  '#181818',
'header_minicart_editCartButton_textColor_' =>  '#ffffff',
'header_minicart_checkoutButton_BgColor_' =>  '#ffffff',
'header_minicart_checkoutButton_textColor_' =>  '#181818',
);
$menuSetting_DefaultConfig_autoDefault= array(
'megaMenu_menu_arrow_' =>  'show',
'megaMenu_submenu_arrow_' =>  'show',
'megaMenu_animation_type_' =>  'nothing',
'megaMenu_backgroundcolor_' =>  'transparent',
'megaMenu_backgroundHoverColor_' =>  'transparent',
'megaMenu_textcolor_' =>  '#000000',
'megaMenu_textHoverColor_' =>  '#000000',
'megaMenu_Typography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'uppercase',
  'font-size' => '15px',
),
'megaMenu_topMenuBorderOption_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'none',
  'border-color' => '#f2f2f2',
),
'megaMenu_insideMenuTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'text-transform' => 'none',
),
'megaMenu_insideMenu_backgroundcolor_' =>  '#ffffff',
'megaMenu_insideMenu_Color' =>  '#000000',
'megaMenu_insideMenu_TextHoverColor_' =>  '#000000',
'megaMenu_insideMenu_ActiveBgColor_' =>  'transparent',
'megaMenu_insideMenu_ActiveTextColor_' =>  'transparent',
'megaMenu_insideMenu_borderOption_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'none',
  'border-color' => '#f2f2f2',
),
'dropdown_menu-border-bottom_text_option_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '1px',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '#f2f2f2',
),
);
$mobileMenuSetting_DefaultConfig_autoDefault= array(
'MobileMenu_BgColor_' =>  '#ffffff',
'MobileMenu_Submenu_BgColor_' =>  '#ffffff',
'MobileMenu_linkColor_' =>  '#000000',
'MobileMenu_arrowColor_' =>  '#000000',
'MobileMenu_searchButtonBgColor_' =>  '#ffffff',
'MobileMenu_searchButtonBorderColor_' =>  '',
'MobileMenu_searchButtonTextColor_' =>  '#000000',
);
$MobileMenuAdvancedSettings_DefaultConfig_autoDefault= array(
'OutSideSidebar_BgColor_' =>  '#ffffff',
'OutSideSidebar_social_EnableDisable_' =>  '#93af76',
'OutSideSidebar_linkColor_' =>  '#8c8c8c',
'OutSideSidebar_arrowColor_' =>  '#8c8c8c',
'OutSideSidebar_searchButtonBgColor_' =>  '#ffffff',
'OutSideSidebar_searchButtonBorderColor_' =>  '#8c8c8c',
'OutSideSidebar_searchButtonTextColor_' =>  '#000000',
);
$blogPostListStyle_DefaultConfig_autoDefault= array(
'BlogPostTitleStyleTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-backup' => '',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '24px',
  'line-height' => '32px',
  'color' => '#333',
),
'BlogPostStyleInfoTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '17px',
  'color' => '#c1c0c0',
),
'BlogPostStyleTextTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '14px',
  'line-height' => '22px',
  'color' => '#333',
),
'PostStyleListBgColor_' =>  'transparent',
'PostStyleListBoxShadow_' =>  '0',
'PostStyleListBorderRadius_' =>  '0',
'PostStyleListBorder_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '0',
  'border-left' => '0',
  'border-style' => 'none',
  'border-color' => '',
),
'PostStyleListSocialBarBgColor_' =>  'transparent',
'PostStyleList_TagTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'capitalize',
  'font-size' => '14px',
  'line-height' => '14px',
  'color' => '#000000',
),
'PostStyleList_TagHoverTypography_' =>  array (
  'font-family' => '',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'capitalize',
  'font-size' => '14px',
  'line-height' => '14px',
  'color' => '#000000',
),
'PostStyleList_TagsBgColor_' =>  '#ffffff',
'PostStyleList_TagsHoverBgColor_' =>  '#ffffff',
'PostStyleList_SocialBarBorder_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '0',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '',
),
'PostStyleList_ReadMoreButtonBgColor_' =>  '#acb7c0',
'PostStyleList_ReadMoreButtonBgHoverColor_' =>  '#acb7c0',
'BlogPostStyleReadMoreButtonTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '15px',
  'line-height' => '14px',
  'color' => '#ffffff',
),
'BlogPostStyleReadMoreButtonHoverTypography_' =>  '#ffffff',
);
$sidebarStyle_DefaultConfig_autoDefault= array(
'sidebar_view_model_' =>  'unboxed',
'sidebar_widget_BgColor_' =>  'transparent',
'sidebar_widget_Border_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'none',
  'border-color' => '#D7D7D7',
),
'sidebar_widgetBoxShadowEnableDisable_' =>  '0',
'sidebar_BoxShadow_BgColor_' =>  array (
  'color' => '',
  'alpha' => '',
  'rgba' => '0,0,0',
),
'sidebar_widget_Linkcolor_' =>  '#000000',
'sidebar_widget_Textcolor_' =>  '#000000',
'sidebar_widget_title_selected' =>  'line_transparant_widget',
'sidebar_widget_title_typography_custom_skin_border_bottom_bg_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'center',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'sidebar_widget_title_typography_custom_skin_border_bottom_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'sidebar_widget_title_typography_custom_skin_line_left_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'sidebar_widget_title_typography_custom_skin_line_transparant_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-align' => 'left',
  'text-transform' => 'uppercase',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'sidebar_widget_title_typography_custom_skin_line_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'center',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'sidebar_widget_title_typography_custom_skin_colored_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'sidebar_widget_title_typography_custom_skin_colored_two_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'sidebar_widget_title_BgColor_first_custom_skin_border_bottom_bg_widget' =>  '#252525',
'sidebar_widget_title_BgColor_first_custom_skin_colored_two_widget' =>  '#252525',
'sidebar_widget_title_BgColor_first_custom_skin_colored_widget' =>  '#252525',
'sidebar_widget_title_BgColor_first_custom_skin_line_widget' =>  '#ffffff',
'sidebar_widget_title_BgColor_first_custom_skin_line_left_widget' =>  '#ffffff',
'sidebar_widget_title_BgColor_second_border_bottom_bg_widget' =>  '#F4524C',
'sidebar_widget_title_BgColor_second_border_bottom_widget' =>  '#F4524C',
'sidebar_widget_title_LineColor' =>  '#000000',
'sidebar_widget_title_colored_widgetTopBorderColor' =>  '#ffc908',
'sidebar_widget_title_borderColor' =>  '',
'sidebar_widget_title_TagbgColor_' =>  '#ffffff',
'sidebar_widget_title_Tag_HoverbgColor_' =>  '#000000',
'sidebar_widget_TagsWidgetBorder_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'solid',
  'border-color' => '#e4e4e4',
),
'sidebar_widget_title_TagWidgetTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '15px',
  'color' => '#000',
),
'sidebar_widget_title_WidgetHoverTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '15px',
  'color' => '#fff',
),
'sidebar_widget_searchButtonBgColor_' =>  '#000000',
'sidebar_widget_searchButton_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '400',
  'font-style' => '',
  'text-transform' => 'uppercase',
  'font-size' => '14px',
  'line-height' => '28px',
  'color' => '#fff',
),
);
$shopsetting_DefaultConfig_autoDefault= array(
'Shop_product_image_bgcolor_' =>  '#eeeeee',
'Shop_sale_badge_textcolor_' =>  '#ffffff',
'Shop_sale_badge_bgcolor_' =>  '#e27c7c',
'Shop_outofstock_badge_bgcolor_' =>  '#8c8c8c',
'Shop_new_badge_bgcolor_' =>  '#dd9933',
'Shop_discountPercentage_' =>  '#dd3333',
'Shop_quickview_bgcolor_' =>  '#b5b5b5',
'AddToCart_btn_BgColor_' =>  '#000000',
'AddToCart_btn_TextColor_' =>  '#ffffff',
);
$FooterStyle_DefaultConfig_autoDefault= array(
'footer_widget_BgColor_' =>  '#bcbcbc',
'footer_widget_Border_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '0',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '',
),
'footer_widget_Linkcolor_' =>  '#aaaaaa',
'footer_widget_Textcolor_' =>  '#aaaaaa',
'footer_widget_title_selected' =>  'line_transparant_widget',
'footer_widget_title_typography_custom_skin_border_bottom_bg_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'center',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'footer_widget_title_typography_custom_skin_border_bottom_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'footer_widget_title_typography_custom_skin_line_left_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'footer_widget_title_typography_custom_skin_line_transparant_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'center',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'footer_widget_title_typography_custom_skin_line_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'center',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#000',
),
'footer_widget_title_typography_custom_skin_colored_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'footer_widget_title_typography_custom_skin_colored_two_widget' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '700',
  'text-align' => 'left',
  'text-transform' => 'none',
  'font-size' => '16px',
  'line-height' => '28px',
  'color' => '#fff',
),
'footer_widget_title_BgColor_first_custom_skin_border_bottom_bg_widget' =>  '#252525',
'footer_widget_title_BgColor_first_custom_skin_colored_two_widget' =>  '#252525',
'footer_widget_title_BgColor_first_custom_skin_colored_widget' =>  '#252525',
'footer_widget_title_BgColor_first_custom_skin_line_widget' =>  '#ffffff',
'footer_widget_title_BgColor_first_custom_skin_line_left_widget' =>  '#ffffff',
'footer_widget_title_BgColor_second_border_bottom_bg_widget' =>  '#F4524C',
'footer_widget_title_BgColor_second_border_bottom_widget' =>  '#F4524C',
'footer_widget_title_LineColor' =>  '#000000',
'footer_widget_title_top_borderColor' =>  '#ffc908',
'footer_widget_title_borderColor' =>  '',
'footer_widget_title_TagbgColor_' =>  '#ffffff',
'footer_widget_title_Tag_HoverbgColor_' =>  '#000000',
'footer_widget_TagsWidgetBorder_' =>  array (
  'border-top' => '1px',
  'border-right' => '1px',
  'border-bottom' => '1px',
  'border-left' => '1px',
  'border-style' => 'solid',
  'border-color' => '#e4e4e4',
),
'footer_widget_title_TagWidgetTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '400',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '15px',
  'color' => '#000',
),
'footer_widget_title_TagWidgetHoverTypography_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '400',
  'text-transform' => 'none',
  'font-size' => '12px',
  'line-height' => '15px',
  'color' => '#fff',
),
'footer_widget_searchButtonBgColor_' =>  '#000000',
'footer_widget_searchButton_' =>  array (
  'font-family' => 'Roboto Condensed',
  'font-options' => '',
  'google' => '1',
  'font-weight' => '',
  'font-style' => '400',
  'text-transform' => 'uppercase',
  'font-size' => '14px',
  'line-height' => '28px',
  'color' => '#fff',
),
'footer_minimal_widget_BgColor_' =>  '#51575a',
'footer_minimal_widget_Border_' =>  array (
  'border-top' => '0',
  'border-right' => '0',
  'border-bottom' => '0',
  'border-left' => '0',
  'border-style' => 'solid',
  'border-color' => '',
),
'footer_minimal_widget_Linkcolor_' =>  '#000000',
'footer_minimal_widget_Textcolor_' =>  '#000000',
);
